
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author francisco.perdomo
 */
public class Menu extends javax.swing.JFrame {
    BaseDeDatos1 bdd = new BaseDeDatos1();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        bdenuncia.setVisible(false);
        bbuscar.setVisible(false);
        ibus.setVisible(false);
        iden.setVisible(false);
    }

    
    public boolean chequearCI(){
        boolean resultado = true;
        if (ci.getText().compareTo("")!=0){
            try {
                lerrorci.setText("");
                ResultSet rs = bdd.enviarConsulta("SELECT * FROM persona where ci="+ci.getText());
                if (!rs.next()) {
                    lerrorci.setText("Ese usuario no está en el sistema");
                    resultado = false;
                }             
            } catch (SQLException ex) {
                Logger.getLogger(BuscarMascota.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            lerrorci.setText("La cédula no puede ser vacía");
            resultado = false;
        }
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        bdenuncia = new javax.swing.JButton();
        bbuscar = new javax.swing.JButton();
        iper = new javax.swing.JLabel();
        imas = new javax.swing.JLabel();
        ibus = new javax.swing.JLabel();
        iden = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        lCI = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lerrorci = new javax.swing.JLabel();
        lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setMaximumSize(new java.awt.Dimension(400, 320));
        Fondo.setMinimumSize(new java.awt.Dimension(400, 320));
        Fondo.setPreferredSize(new java.awt.Dimension(400, 320));
        Fondo.setRequestFocusEnabled(false);
        Fondo.setLayout(null);

        Titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 78, 150));
        Titulo.setText("Menu");
        Fondo.add(Titulo);
        Titulo.setBounds(80, 30, 110, 50);

        bdenuncia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bdenuncia.setText("Hacer Denuncia");
        bdenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdenunciaActionPerformed(evt);
            }
        });
        Fondo.add(bdenuncia);
        bdenuncia.setBounds(110, 200, 150, 20);

        bbuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bbuscar.setText("Buscar Mascota");
        bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarActionPerformed(evt);
            }
        });
        Fondo.add(bbuscar);
        bbuscar.setBounds(110, 250, 150, 20);

        iper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/persona.jpg"))); // NOI18N
        Fondo.add(iper);
        iper.setBounds(180, 130, 20, 20);

        imas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pata.jpg"))); // NOI18N
        Fondo.add(imas);
        imas.setBounds(200, 50, 20, 20);

        ibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        Fondo.add(ibus);
        ibus.setBounds(300, 250, 20, 20);

        iden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exclamacion.jpg"))); // NOI18N
        Fondo.add(iden);
        iden.setBounds(300, 200, 20, 20);
        Fondo.add(ci);
        ci.setBounds(20, 130, 150, 30);

        lCI.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lCI.setForeground(new java.awt.Color(0, 78, 150));
        lCI.setText("Ingresa tu CI");
        Fondo.add(lCI);
        lCI.setBounds(20, 110, 100, 14);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Fondo.add(jButton1);
        jButton1.setBounds(30, 170, 120, 23);

        lerrorci.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lerrorci.setForeground(new java.awt.Color(255, 0, 0));
        lerrorci.setText("     ");
        Fondo.add(lerrorci);
        lerrorci.setBounds(210, 130, 170, 20);

        lfondo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuFondo.jpg"))); // NOI18N
        Fondo.add(lfondo);
        lfondo.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdenunciaActionPerformed
        new Denuncia(Integer.parseInt(ci.getText())).setVisible(true);
    }//GEN-LAST:event_bdenunciaActionPerformed

    private void bbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarActionPerformed
        new BuscarMascota(Integer.parseInt(ci.getText())).setVisible(true);
    }//GEN-LAST:event_bbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean ciOK = chequearCI();
        if (ciOK){
            bdenuncia.setVisible(true);
            bbuscar.setVisible(true);
            ibus.setVisible(true);
            iden.setVisible(true);
            lCI.setText("Bienvenido");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton bdenuncia;
    private javax.swing.JTextField ci;
    private javax.swing.JLabel ibus;
    private javax.swing.JLabel iden;
    private javax.swing.JLabel imas;
    private javax.swing.JLabel iper;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lCI;
    private javax.swing.JLabel lerrorci;
    private javax.swing.JLabel lfondo;
    // End of variables declaration//GEN-END:variables
}
